import type {
  CharacterRecord,
  NarrativeSegmentRecord,
  PlayRecord,
  RelationRecord,
  ThemeRecord,
} from './types'

export const plays: PlayRecord[] = [
  {
    id: 'zuoloushaxi',
    title: '坐楼杀惜',
    period: '清代',
    genre: '公案戏',
    authorEra: '清代舞台整理本',
    sceneCount: 6,
    narrativePattern: '快冲突型',
    summary: '围绕宋江、阎惜姣与张文远展开，情感背叛与权力失衡快速推动剧情走向暴烈高潮。',
  },
  {
    id: 'zhaoshiguer',
    title: '赵氏孤儿',
    period: '元代',
    genre: '历史戏',
    authorEra: '元杂剧',
    sceneCount: 7,
    narrativePattern: '单主角推进型',
    summary: '忠义与复仇交织，以家国大义推动人物牺牲与历史抉择。',
  },
  {
    id: 'doueyuan',
    title: '窦娥冤',
    period: '元代',
    genre: '公案戏',
    authorEra: '元杂剧',
    sceneCount: 6,
    narrativePattern: '线性审判型',
    summary: '冤案与伦理失序层层叠加，推动女性悲剧与天道昭雪的叙事结构。',
  },
  {
    id: 'qinxianglian',
    title: '秦香莲',
    period: '清代',
    genre: '家庭戏',
    authorEra: '清代梆子系统',
    sceneCount: 7,
    narrativePattern: '双高潮型',
    summary: '家庭伦理、仕途背叛与法理裁断并存，角色关系由家庭单元裂解为审判结构。',
  },
  {
    id: 'dajinzhi',
    title: '打金枝',
    period: '清代',
    genre: '家庭戏',
    authorEra: '清传奇',
    sceneCount: 5,
    narrativePattern: '慢铺垫型',
    summary: '宫廷姻亲冲突在礼制与亲情调和中逐步升级，最终回归秩序。',
  },
  {
    id: 'xixiangji',
    title: '西厢记',
    period: '元代',
    genre: '爱情戏',
    authorEra: '元杂剧',
    sceneCount: 7,
    narrativePattern: '情感递进型',
    summary: '才子佳人故事通过媒合、阻隔与转机形成细密的情感推进。',
  },
  {
    id: 'mudanting',
    title: '牡丹亭',
    period: '明代',
    genre: '爱情戏',
    authorEra: '明传奇',
    sceneCount: 8,
    narrativePattern: '双线抒情型',
    summary: '梦境、情感与生死越界并行推进，叙事节奏富于抒情停顿与高潮回返。',
  },
  {
    id: 'pipaji',
    title: '琵琶记',
    period: '明代',
    genre: '家庭戏',
    authorEra: '南戏系统',
    sceneCount: 8,
    narrativePattern: '伦理回环型',
    summary: '围绕孝义、婚姻与仕途形成多线并进的家庭伦理结构。',
  },
]

export const characters: CharacterRecord[] = [
  {
    id: 'c-songjiang',
    playId: 'zuoloushaxi',
    name: '宋江',
    gender: '男',
    ageGroup: '中年',
    identity: '郓城押司',
    personalityTags: ['克制', '隐忍', '威严'],
    roleMain: '生',
    roleSubtype: '老生',
    confidence: 0.92,
    actionScore: 69,
    emotionScore: 58,
    appearanceCount: 8,
    evidence: ['身份偏官绅', '语气压抑克制', '冲突中以控制和决断推动局势'],
  },
  {
    id: 'c-yanxijiao',
    playId: 'zuoloushaxi',
    name: '阎惜姣',
    gender: '女',
    ageGroup: '青年',
    identity: '妾室',
    personalityTags: ['敏感', '锋利', '情绪外显'],
    roleMain: '旦',
    roleSubtype: '花旦',
    confidence: 0.95,
    actionScore: 73,
    emotionScore: 91,
    appearanceCount: 9,
    evidence: ['年轻女性', '唱念情绪浓烈', '直接推动关键冲突'],
  },
  {
    id: 'c-yanpo',
    playId: 'zuoloushaxi',
    name: '阎婆',
    gender: '女',
    ageGroup: '老年',
    identity: '母亲',
    personalityTags: ['圆滑', '强势', '世故'],
    roleMain: '旦',
    roleSubtype: '彩旦',
    confidence: 0.87,
    actionScore: 55,
    emotionScore: 72,
    appearanceCount: 6,
    evidence: ['年长女性', '语言辛辣', '插科与推动矛盾并存'],
  },
  {
    id: 'c-zhangwenyuan',
    playId: 'zuoloushaxi',
    name: '张文远',
    gender: '男',
    ageGroup: '青年',
    identity: '书吏',
    personalityTags: ['轻佻', '机巧', '暧昧'],
    roleMain: '生',
    roleSubtype: '小生',
    confidence: 0.88,
    actionScore: 48,
    emotionScore: 67,
    appearanceCount: 5,
    evidence: ['青年书生身份', '情爱互动多', '以风流气质呈现'],
  },
  {
    id: 'c-tangniuer',
    playId: 'zuoloushaxi',
    name: '唐牛儿',
    gender: '男',
    ageGroup: '成年',
    identity: '市井闲汉',
    personalityTags: ['滑稽', '插科', '机敏'],
    roleMain: '丑',
    roleSubtype: '文丑',
    confidence: 0.9,
    actionScore: 52,
    emotionScore: 49,
    appearanceCount: 4,
    evidence: ['市井身份鲜明', '承担过渡和点染功能', '语词偏口语化'],
  },
  {
    id: 'c-chengying',
    playId: 'zhaoshiguer',
    name: '程婴',
    gender: '男',
    ageGroup: '中年',
    identity: '义士',
    personalityTags: ['忠义', '果决', '沉稳'],
    roleMain: '生',
    roleSubtype: '老生',
    confidence: 0.96,
    actionScore: 84,
    emotionScore: 70,
    appearanceCount: 10,
    evidence: ['家国重任在身', '牺牲与抉择突出', '唱念庄重'],
  },
  {
    id: 'c-gongsunchujiu',
    playId: 'zhaoshiguer',
    name: '公孙杵臼',
    gender: '男',
    ageGroup: '老年',
    identity: '忠臣',
    personalityTags: ['刚烈', '耿直', '忠诚'],
    roleMain: '生',
    roleSubtype: '老生',
    confidence: 0.94,
    actionScore: 60,
    emotionScore: 62,
    appearanceCount: 5,
    evidence: ['老臣形象', '以道义自持', '舞台呈现厚重'],
  },
  {
    id: 'c-tuanangu',
    playId: 'zhaoshiguer',
    name: '屠岸贾',
    gender: '男',
    ageGroup: '中年',
    identity: '权臣',
    personalityTags: ['阴狠', '专横', '冷酷'],
    roleMain: '净',
    roleSubtype: '大花脸',
    confidence: 0.97,
    actionScore: 77,
    emotionScore: 64,
    appearanceCount: 7,
    evidence: ['权臣反派', '情绪强烈外放', '形体与声腔强调压迫感'],
  },
  {
    id: 'c-zhaowu',
    playId: 'zhaoshiguer',
    name: '赵武',
    gender: '男',
    ageGroup: '青年',
    identity: '孤儿后裔',
    personalityTags: ['隐忍', '觉醒', '正直'],
    roleMain: '生',
    roleSubtype: '小生',
    confidence: 0.86,
    actionScore: 70,
    emotionScore: 72,
    appearanceCount: 6,
    evidence: ['青年成长线突出', '承接复仇使命', '语气逐渐昂扬'],
  },
  {
    id: 'c-hanchueji',
    playId: 'zhaoshiguer',
    name: '韩厥',
    gender: '男',
    ageGroup: '成年',
    identity: '将领',
    personalityTags: ['正直', '忠勇', '简练'],
    roleMain: '生',
    roleSubtype: '武生',
    confidence: 0.84,
    actionScore: 88,
    emotionScore: 51,
    appearanceCount: 4,
    evidence: ['行动性强', '军中身份鲜明', '做打成分较多'],
  },
  {
    id: 'c-doue',
    playId: 'doueyuan',
    name: '窦娥',
    gender: '女',
    ageGroup: '青年',
    identity: '寡妇',
    personalityTags: ['贞烈', '坚韧', '悲愤'],
    roleMain: '旦',
    roleSubtype: '青衣',
    confidence: 0.98,
    actionScore: 62,
    emotionScore: 95,
    appearanceCount: 10,
    evidence: ['悲剧女性核心', '唱段抒情浓烈', '伦理与冤屈并重'],
  },
  {
    id: 'c-tsaipo',
    playId: 'doueyuan',
    name: '蔡婆',
    gender: '女',
    ageGroup: '老年',
    identity: '婆母',
    personalityTags: ['软弱', '善良', '受制'],
    roleMain: '旦',
    roleSubtype: '老旦',
    confidence: 0.89,
    actionScore: 35,
    emotionScore: 56,
    appearanceCount: 5,
    evidence: ['年长妇人', '亲属关系核心', '以念白承接伦理线'],
  },
  {
    id: 'c-zhangluer',
    playId: 'doueyuan',
    name: '张驴儿',
    gender: '男',
    ageGroup: '成年',
    identity: '恶棍',
    personalityTags: ['无赖', '阴险', '粗暴'],
    roleMain: '丑',
    roleSubtype: '武丑',
    confidence: 0.81,
    actionScore: 71,
    emotionScore: 61,
    appearanceCount: 6,
    evidence: ['恶棍市井属性明显', '动作挑衅性强', '兼具滑稽与邪性'],
  },
  {
    id: 'c-taishou',
    playId: 'doueyuan',
    name: '贪官太守',
    gender: '男',
    ageGroup: '中年',
    identity: '地方官',
    personalityTags: ['昏庸', '傲慢', '专断'],
    roleMain: '净',
    roleSubtype: '二花脸',
    confidence: 0.83,
    actionScore: 44,
    emotionScore: 52,
    appearanceCount: 4,
    evidence: ['官场权威角色', '偏外化与脸谱化', '审案场面突出'],
  },
  {
    id: 'c-taohangzhang',
    playId: 'doueyuan',
    name: '桃杌',
    gender: '男',
    ageGroup: '成年',
    identity: '衙役',
    personalityTags: ['冷漠', '服从', '工具化'],
    roleMain: '丑',
    roleSubtype: '文丑',
    confidence: 0.76,
    actionScore: 43,
    emotionScore: 33,
    appearanceCount: 3,
    evidence: ['承担衙门场面调度', '人物功能性较强', '口语化明显'],
  },
  {
    id: 'c-qinxianglian',
    playId: 'qinxianglian',
    name: '秦香莲',
    gender: '女',
    ageGroup: '青年',
    identity: '妻子',
    personalityTags: ['坚毅', '悲苦', '守节'],
    roleMain: '旦',
    roleSubtype: '青衣',
    confidence: 0.97,
    actionScore: 68,
    emotionScore: 90,
    appearanceCount: 9,
    evidence: ['核心苦情女性', '唱段重控诉与自持', '伦理冲突承担者'],
  },
  {
    id: 'c-chenshimai',
    playId: 'qinxianglian',
    name: '陈世美',
    gender: '男',
    ageGroup: '青年',
    identity: '驸马',
    personalityTags: ['负心', '虚荣', '退缩'],
    roleMain: '生',
    roleSubtype: '小生',
    confidence: 0.85,
    actionScore: 51,
    emotionScore: 55,
    appearanceCount: 7,
    evidence: ['青年官员气质', '风流而失德', '以念白和对峙推进剧情'],
  },
  {
    id: 'c-baozheng',
    playId: 'qinxianglian',
    name: '包拯',
    gender: '男',
    ageGroup: '中年',
    identity: '清官',
    personalityTags: ['刚正', '威严', '明断'],
    roleMain: '净',
    roleSubtype: '包公',
    confidence: 0.99,
    actionScore: 65,
    emotionScore: 58,
    appearanceCount: 8,
    evidence: ['标志性净角类型', '审判场面居中', '脸谱与声腔特征强'],
  },
  {
    id: 'c-guifei',
    playId: 'qinxianglian',
    name: '皇姑',
    gender: '女',
    ageGroup: '中年',
    identity: '皇亲',
    personalityTags: ['高傲', '护短', '威势'],
    roleMain: '旦',
    roleSubtype: '正旦',
    confidence: 0.78,
    actionScore: 37,
    emotionScore: 44,
    appearanceCount: 3,
    evidence: ['中年贵妇人设', '礼制身份突出', '舞台重仪态'],
  },
  {
    id: 'c-wangyanling',
    playId: 'qinxianglian',
    name: '王延龄',
    gender: '男',
    ageGroup: '老年',
    identity: '朝臣',
    personalityTags: ['圆融', '审慎', '斡旋'],
    roleMain: '生',
    roleSubtype: '老生',
    confidence: 0.82,
    actionScore: 30,
    emotionScore: 35,
    appearanceCount: 3,
    evidence: ['老臣斡旋者', '台步与念白稳重', '功能偏制度调停'],
  },
  {
    id: 'c-guoyiai',
    playId: 'dajinzhi',
    name: '郭暧',
    gender: '男',
    ageGroup: '青年',
    identity: '驸马',
    personalityTags: ['倨傲', '率真', '冲动'],
    roleMain: '生',
    roleSubtype: '小生',
    confidence: 0.84,
    actionScore: 65,
    emotionScore: 70,
    appearanceCount: 6,
    evidence: ['青年贵公子', '夫妻冲突集中', '情绪外放但不失风流'],
  },
  {
    id: 'c-shengping',
    playId: 'dajinzhi',
    name: '升平公主',
    gender: '女',
    ageGroup: '青年',
    identity: '公主',
    personalityTags: ['骄矜', '聪慧', '敏感'],
    roleMain: '旦',
    roleSubtype: '闺门旦',
    confidence: 0.88,
    actionScore: 52,
    emotionScore: 78,
    appearanceCount: 6,
    evidence: ['青年贵族女性', '礼法与情感冲突显著', '唱段细腻'],
  },
  {
    id: 'c-guoziyi',
    playId: 'dajinzhi',
    name: '郭子仪',
    gender: '男',
    ageGroup: '老年',
    identity: '老臣',
    personalityTags: ['稳重', '忠厚', '权威'],
    roleMain: '生',
    roleSubtype: '老生',
    confidence: 0.93,
    actionScore: 38,
    emotionScore: 42,
    appearanceCount: 4,
    evidence: ['老臣形象', '以调停和教诲为主', '念白庄重'],
  },
  {
    id: 'c-tangdizhu',
    playId: 'dajinzhi',
    name: '唐帝',
    gender: '男',
    ageGroup: '中年',
    identity: '皇帝',
    personalityTags: ['威严', '宽缓', '调和'],
    roleMain: '生',
    roleSubtype: '外',
    confidence: 0.77,
    actionScore: 31,
    emotionScore: 33,
    appearanceCount: 3,
    evidence: ['帝王身份', '场面调和功能强', '仪态重于动作'],
  },
  {
    id: 'c-neishi',
    playId: 'dajinzhi',
    name: '内侍',
    gender: '男',
    ageGroup: '成年',
    identity: '宫人',
    personalityTags: ['机灵', '灵活', '点染'],
    roleMain: '丑',
    roleSubtype: '文丑',
    confidence: 0.8,
    actionScore: 40,
    emotionScore: 29,
    appearanceCount: 2,
    evidence: ['承担场面转换', '口语化强', '轻松化宫廷氛围'],
  },
  {
    id: 'c-zhangsheng',
    playId: 'xixiangji',
    name: '张生',
    gender: '男',
    ageGroup: '青年',
    identity: '书生',
    personalityTags: ['痴情', '文雅', '执着'],
    roleMain: '生',
    roleSubtype: '小生',
    confidence: 0.95,
    actionScore: 46,
    emotionScore: 87,
    appearanceCount: 9,
    evidence: ['才子形象典型', '唱念偏抒情', '情感持续推动剧情'],
  },
  {
    id: 'c-cuiyingying',
    playId: 'xixiangji',
    name: '崔莺莺',
    gender: '女',
    ageGroup: '青年',
    identity: '相府小姐',
    personalityTags: ['含蓄', '坚定', '细腻'],
    roleMain: '旦',
    roleSubtype: '闺门旦',
    confidence: 0.97,
    actionScore: 44,
    emotionScore: 90,
    appearanceCount: 8,
    evidence: ['闺阁女性', '情感层次丰富', '声腔细腻委婉'],
  },
  {
    id: 'c-hongniang',
    playId: 'xixiangji',
    name: '红娘',
    gender: '女',
    ageGroup: '青年',
    identity: '侍女',
    personalityTags: ['机智', '活泼', '善辩'],
    roleMain: '旦',
    roleSubtype: '花旦',
    confidence: 0.93,
    actionScore: 59,
    emotionScore: 74,
    appearanceCount: 8,
    evidence: ['活泼侍女', '调度情节功能强', '念白灵动'],
  },
  {
    id: 'c-laofuren',
    playId: 'xixiangji',
    name: '老夫人',
    gender: '女',
    ageGroup: '中年',
    identity: '母亲',
    personalityTags: ['威严', '守礼', '控制'],
    roleMain: '旦',
    roleSubtype: '正旦',
    confidence: 0.82,
    actionScore: 26,
    emotionScore: 48,
    appearanceCount: 4,
    evidence: ['家长角色', '规范与秩序代表', '台词以礼法裁定为主'],
  },
  {
    id: 'c-heshang',
    playId: 'xixiangji',
    name: '法本和尚',
    gender: '男',
    ageGroup: '成年',
    identity: '寺僧',
    personalityTags: ['平和', '机敏', '点染'],
    roleMain: '丑',
    roleSubtype: '文丑',
    confidence: 0.72,
    actionScore: 25,
    emotionScore: 25,
    appearanceCount: 2,
    evidence: ['辅助性角色', '承担场面衔接', '口气活泛'],
  },
  {
    id: 'c-duiniang',
    playId: 'mudanting',
    name: '杜丽娘',
    gender: '女',
    ageGroup: '青年',
    identity: '官宦小姐',
    personalityTags: ['多情', '敏感', '执着'],
    roleMain: '旦',
    roleSubtype: '闺门旦',
    confidence: 0.98,
    actionScore: 48,
    emotionScore: 96,
    appearanceCount: 10,
    evidence: ['闺门抒情核心', '梦境与情欲表达丰富', '细腻唱念突出'],
  },
  {
    id: 'c-liumengmei',
    playId: 'mudanting',
    name: '柳梦梅',
    gender: '男',
    ageGroup: '青年',
    identity: '书生',
    personalityTags: ['痴情', '儒雅', '执拗'],
    roleMain: '生',
    roleSubtype: '小生',
    confidence: 0.94,
    actionScore: 40,
    emotionScore: 85,
    appearanceCount: 7,
    evidence: ['青年书生', '情爱线承担者', '唱念偏文雅抒情'],
  },
  {
    id: 'c-chunxiang',
    playId: 'mudanting',
    name: '春香',
    gender: '女',
    ageGroup: '青年',
    identity: '侍女',
    personalityTags: ['活泼', '忠心', '伶俐'],
    roleMain: '旦',
    roleSubtype: '花旦',
    confidence: 0.92,
    actionScore: 57,
    emotionScore: 63,
    appearanceCount: 6,
    evidence: ['侍女机敏灵动', '为小姐情感线服务', '念白轻快'],
  },
  {
    id: 'c-dubao',
    playId: 'mudanting',
    name: '杜宝',
    gender: '男',
    ageGroup: '中年',
    identity: '父亲',
    personalityTags: ['严厉', '守礼', '保守'],
    roleMain: '生',
    roleSubtype: '外',
    confidence: 0.79,
    actionScore: 29,
    emotionScore: 36,
    appearanceCount: 4,
    evidence: ['父权角色', '制度与家法象征', '舞台重身份仪态'],
  },
  {
    id: 'c-huaqiang',
    playId: 'mudanting',
    name: '花神',
    gender: '女',
    ageGroup: '成年',
    identity: '神灵',
    personalityTags: ['空灵', '引导', '象征'],
    roleMain: '旦',
    roleSubtype: '花衫',
    confidence: 0.74,
    actionScore: 22,
    emotionScore: 58,
    appearanceCount: 2,
    evidence: ['舞台象征性强', '场面偏抒情仪式', '服饰与身段突出'],
  },
  {
    id: 'c-zhaowuniang',
    playId: 'pipaji',
    name: '赵五娘',
    gender: '女',
    ageGroup: '青年',
    identity: '妻子',
    personalityTags: ['孝顺', '坚忍', '贤淑'],
    roleMain: '旦',
    roleSubtype: '青衣',
    confidence: 0.97,
    actionScore: 58,
    emotionScore: 88,
    appearanceCount: 9,
    evidence: ['贤妻孝妇典型', '伦理叙事中心', '唱段悲苦克制'],
  },
  {
    id: 'c-caibojie',
    playId: 'pipaji',
    name: '蔡伯喈',
    gender: '男',
    ageGroup: '青年',
    identity: '书生',
    personalityTags: ['孝义', '犹疑', '被动'],
    roleMain: '生',
    roleSubtype: '小生',
    confidence: 0.88,
    actionScore: 43,
    emotionScore: 69,
    appearanceCount: 7,
    evidence: ['书生仕途线主角', '内心挣扎多', '念白抒情兼具'],
  },
  {
    id: 'c-caigong',
    playId: 'pipaji',
    name: '蔡公',
    gender: '男',
    ageGroup: '老年',
    identity: '父亲',
    personalityTags: ['衰弱', '慈爱', '守礼'],
    roleMain: '生',
    roleSubtype: '老生',
    confidence: 0.91,
    actionScore: 21,
    emotionScore: 41,
    appearanceCount: 4,
    evidence: ['老父形象', '伦理牵引作用强', '以念白和身段传达衰老'],
  },
  {
    id: 'c-niuxiaojie',
    playId: 'pipaji',
    name: '牛小姐',
    gender: '女',
    ageGroup: '青年',
    identity: '新妇',
    personalityTags: ['端庄', '矛盾', '温和'],
    roleMain: '旦',
    roleSubtype: '正旦',
    confidence: 0.77,
    actionScore: 30,
    emotionScore: 54,
    appearanceCount: 4,
    evidence: ['闺阁女性', '家内身份复杂', '以礼法和情分承接冲突'],
  },
  {
    id: 'c-laoniang',
    playId: 'pipaji',
    name: '蔡母',
    gender: '女',
    ageGroup: '老年',
    identity: '母亲',
    personalityTags: ['慈苦', '隐忍', '衰病'],
    roleMain: '旦',
    roleSubtype: '老旦',
    confidence: 0.9,
    actionScore: 18,
    emotionScore: 47,
    appearanceCount: 4,
    evidence: ['病弱母亲形象', '伦理悲剧色彩浓', '念白与哭腔突出'],
  },
]

export const relations: RelationRecord[] = [
  { playId: 'zuoloushaxi', source: 'c-songjiang', target: 'c-yanxijiao', relationType: '爱情/冲突', weight: 9, scenes: ['第1场', '第4场', '第5场'] },
  { playId: 'zuoloushaxi', source: 'c-yanxijiao', target: 'c-zhangwenyuan', relationType: '私情', weight: 7, scenes: ['第2场', '第3场'] },
  { playId: 'zuoloushaxi', source: 'c-yanpo', target: 'c-yanxijiao', relationType: '母女', weight: 5, scenes: ['第1场', '第2场'] },
  { playId: 'zuoloushaxi', source: 'c-tangniuer', target: 'c-songjiang', relationType: '消息传递', weight: 4, scenes: ['第3场'] },
  { playId: 'zhaoshiguer', source: 'c-chengying', target: 'c-zhaowu', relationType: '保护/抚养', weight: 8, scenes: ['第2场', '第5场'] },
  { playId: 'zhaoshiguer', source: 'c-chengying', target: 'c-tuanangu', relationType: '政治对抗', weight: 9, scenes: ['第1场', '第6场'] },
  { playId: 'zhaoshiguer', source: 'c-gongsunchujiu', target: 'c-chengying', relationType: '忠义同盟', weight: 7, scenes: ['第1场'] },
  { playId: 'zhaoshiguer', source: 'c-hanchueji', target: 'c-chengying', relationType: '援助', weight: 5, scenes: ['第2场'] },
  { playId: 'doueyuan', source: 'c-doue', target: 'c-tsaipo', relationType: '婆媳', weight: 6, scenes: ['第1场', '第2场'] },
  { playId: 'doueyuan', source: 'c-doue', target: 'c-zhangluer', relationType: '迫害/冲突', weight: 9, scenes: ['第2场', '第3场'] },
  { playId: 'doueyuan', source: 'c-doue', target: 'c-taishou', relationType: '冤案审判', weight: 8, scenes: ['第4场'] },
  { playId: 'doueyuan', source: 'c-zhangluer', target: 'c-taishou', relationType: '贿赂/利用', weight: 4, scenes: ['第4场'] },
  { playId: 'qinxianglian', source: 'c-qinxianglian', target: 'c-chenshimai', relationType: '夫妻/冲突', weight: 9, scenes: ['第1场', '第3场'] },
  { playId: 'qinxianglian', source: 'c-baozheng', target: 'c-chenshimai', relationType: '审判', weight: 8, scenes: ['第5场', '第6场'] },
  { playId: 'qinxianglian', source: 'c-qinxianglian', target: 'c-baozheng', relationType: '申诉', weight: 7, scenes: ['第4场', '第5场'] },
  { playId: 'qinxianglian', source: 'c-guifei', target: 'c-chenshimai', relationType: '皇亲庇护', weight: 4, scenes: ['第4场'] },
  { playId: 'dajinzhi', source: 'c-guoyiai', target: 'c-shengping', relationType: '夫妻/冲突', weight: 8, scenes: ['第2场', '第3场'] },
  { playId: 'dajinzhi', source: 'c-guoziyi', target: 'c-guoyiai', relationType: '父子', weight: 5, scenes: ['第3场'] },
  { playId: 'dajinzhi', source: 'c-tangdizhu', target: 'c-shengping', relationType: '父女', weight: 5, scenes: ['第4场'] },
  { playId: 'dajinzhi', source: 'c-neishi', target: 'c-shengping', relationType: '侍从', weight: 2, scenes: ['第1场'] },
  { playId: 'xixiangji', source: 'c-zhangsheng', target: 'c-cuiyingying', relationType: '爱情', weight: 9, scenes: ['第2场', '第4场', '第6场'] },
  { playId: 'xixiangji', source: 'c-hongniang', target: 'c-cuiyingying', relationType: '主仆/盟友', weight: 7, scenes: ['第2场', '第5场'] },
  { playId: 'xixiangji', source: 'c-hongniang', target: 'c-zhangsheng', relationType: '媒合', weight: 6, scenes: ['第3场', '第5场'] },
  { playId: 'xixiangji', source: 'c-laofuren', target: 'c-cuiyingying', relationType: '母女/约束', weight: 5, scenes: ['第1场', '第6场'] },
  { playId: 'mudanting', source: 'c-duiniang', target: 'c-liumengmei', relationType: '爱情', weight: 9, scenes: ['第2场', '第6场'] },
  { playId: 'mudanting', source: 'c-chunxiang', target: 'c-duiniang', relationType: '主仆/陪伴', weight: 6, scenes: ['第1场', '第2场'] },
  { playId: 'mudanting', source: 'c-dubao', target: 'c-duiniang', relationType: '父女/约束', weight: 5, scenes: ['第1场', '第5场'] },
  { playId: 'mudanting', source: 'c-huaqiang', target: 'c-duiniang', relationType: '象征引导', weight: 3, scenes: ['第2场'] },
  { playId: 'pipaji', source: 'c-zhaowuniang', target: 'c-caibojie', relationType: '夫妻/离散', weight: 8, scenes: ['第1场', '第5场'] },
  { playId: 'pipaji', source: 'c-zhaowuniang', target: 'c-caigong', relationType: '孝养', weight: 7, scenes: ['第2场', '第3场'] },
  { playId: 'pipaji', source: 'c-zhaowuniang', target: 'c-laoniang', relationType: '婆媳', weight: 6, scenes: ['第2场'] },
  { playId: 'pipaji', source: 'c-caibojie', target: 'c-niuxiaojie', relationType: '再婚/礼法', weight: 4, scenes: ['第6场'] },
]

export const themes: ThemeRecord[] = [
  { playId: 'zuoloushaxi', theme: '爱情', weight: 7, evidenceSegments: ['私情线快速升温'] },
  { playId: 'zuoloushaxi', theme: '背叛', weight: 8, evidenceSegments: ['信任崩塌引发杀机'] },
  { playId: 'zuoloushaxi', theme: '欲望', weight: 7, evidenceSegments: ['情欲与占有欲相互缠绕'] },
  { playId: 'zuoloushaxi', theme: '暴力', weight: 9, evidenceSegments: ['高潮以暴烈行动收束'] },
  { playId: 'zhaoshiguer', theme: '忠义', weight: 10, evidenceSegments: ['以救孤为核心'] },
  { playId: 'zhaoshiguer', theme: '复仇', weight: 8, evidenceSegments: ['仇怨延迟兑现'] },
  { playId: 'zhaoshiguer', theme: '家国', weight: 9, evidenceSegments: ['私人牺牲服从政治大义'] },
  { playId: 'zhaoshiguer', theme: '牺牲', weight: 8, evidenceSegments: ['人物不断以命相托'] },
  { playId: 'doueyuan', theme: '冤案', weight: 10, evidenceSegments: ['误判与构陷是全剧核心'] },
  { playId: 'doueyuan', theme: '贞节', weight: 7, evidenceSegments: ['窦娥坚守伦理名节'] },
  { playId: 'doueyuan', theme: '报应', weight: 8, evidenceSegments: ['天人感应构成结尾力量'] },
  { playId: 'doueyuan', theme: '伦理', weight: 7, evidenceSegments: ['婆媳与婚姻关系相互牵制'] },
  { playId: 'qinxianglian', theme: '家庭伦理', weight: 10, evidenceSegments: ['妻子申诉与丈夫背弃对置'] },
  { playId: 'qinxianglian', theme: '背叛', weight: 8, evidenceSegments: ['陈世美负义弃妻'] },
  { playId: 'qinxianglian', theme: '法理', weight: 8, evidenceSegments: ['包公主持裁断'] },
  { playId: 'qinxianglian', theme: '女性申诉', weight: 9, evidenceSegments: ['以女性控诉推动转折'] },
  { playId: 'dajinzhi', theme: '家庭伦理', weight: 8, evidenceSegments: ['夫妻与父女关系交织'] },
  { playId: 'dajinzhi', theme: '礼制', weight: 8, evidenceSegments: ['宫廷秩序被冒犯后再重建'] },
  { playId: 'dajinzhi', theme: '权力', weight: 6, evidenceSegments: ['皇家身份加剧冲突'] },
  { playId: 'dajinzhi', theme: '和解', weight: 7, evidenceSegments: ['最终以调停恢复秩序'] },
  { playId: 'xixiangji', theme: '爱情', weight: 10, evidenceSegments: ['爱情为全剧绝对主轴'] },
  { playId: 'xixiangji', theme: '礼法阻隔', weight: 7, evidenceSegments: ['家长与礼法构成外在约束'] },
  { playId: 'xixiangji', theme: '媒合', weight: 8, evidenceSegments: ['红娘串联感情发展'] },
  { playId: 'xixiangji', theme: '青年自主', weight: 6, evidenceSegments: ['情感选择突破等级约束'] },
  { playId: 'mudanting', theme: '爱情', weight: 10, evidenceSegments: ['情至生死相越'] },
  { playId: 'mudanting', theme: '梦境', weight: 8, evidenceSegments: ['梦作为叙事发动机'] },
  { playId: 'mudanting', theme: '生死', weight: 9, evidenceSegments: ['跨越生死的重逢结构'] },
  { playId: 'mudanting', theme: '个体欲望', weight: 8, evidenceSegments: ['主体情感超越礼法'] },
  { playId: 'pipaji', theme: '家庭伦理', weight: 10, evidenceSegments: ['家庭责任贯穿始终'] },
  { playId: 'pipaji', theme: '孝义', weight: 9, evidenceSegments: ['奉亲与仕途冲突'] },
  { playId: 'pipaji', theme: '离散', weight: 8, evidenceSegments: ['夫妻分离与亲族离散'] },
  { playId: 'pipaji', theme: '女性坚忍', weight: 9, evidenceSegments: ['赵五娘承担伦理重压'] },
]

export const narrativeSegments: NarrativeSegmentRecord[] = [
  { playId: 'zuoloushaxi', scene: '第1场', stage: '开端', tension: 28, action: 20, emotion: 40, performanceForm: '念', label: '关系交代', description: '人物关系与潜在张力被快速建立。' },
  { playId: 'zuoloushaxi', scene: '第2场', stage: '铺垫', tension: 45, action: 34, emotion: 56, performanceForm: '唱', label: '私情显露', description: '欲望线与背叛线开始明朗。' },
  { playId: 'zuoloushaxi', scene: '第3场', stage: '冲突升级', tension: 67, action: 61, emotion: 71, performanceForm: '念', label: '消息传递', description: '外部信息加速推动人物对峙。' },
  { playId: 'zuoloushaxi', scene: '第4场', stage: '转折', tension: 82, action: 73, emotion: 80, performanceForm: '做', label: '正面摊牌', description: '主要角色从情感争执进入不可逆对抗。' },
  { playId: 'zuoloushaxi', scene: '第5场', stage: '高潮', tension: 96, action: 90, emotion: 88, performanceForm: '打', label: '暴力爆发', description: '以激烈行动完成高潮与结局。' },
  { playId: 'zuoloushaxi', scene: '第6场', stage: '收束', tension: 54, action: 30, emotion: 60, performanceForm: '念', label: '后果呈现', description: '情节快速收束并留下余震。' },
  { playId: 'zhaoshiguer', scene: '第1场', stage: '开端', tension: 36, action: 33, emotion: 39, performanceForm: '念', label: '祸机初现', description: '政治危机建立起核心使命。' },
  { playId: 'zhaoshiguer', scene: '第2场', stage: '铺垫', tension: 51, action: 47, emotion: 44, performanceForm: '做', label: '救孤布局', description: '忠义同盟形成。' },
  { playId: 'zhaoshiguer', scene: '第3场', stage: '冲突升级', tension: 63, action: 55, emotion: 52, performanceForm: '唱', label: '牺牲抉择', description: '私人牺牲被推到台前。' },
  { playId: 'zhaoshiguer', scene: '第4场', stage: '转折', tension: 74, action: 65, emotion: 61, performanceForm: '念', label: '身份隐匿', description: '故事转入长期潜伏。' },
  { playId: 'zhaoshiguer', scene: '第5场', stage: '冲突升级', tension: 80, action: 72, emotion: 66, performanceForm: '做', label: '真相逼近', description: '赵武逐步接近真相。' },
  { playId: 'zhaoshiguer', scene: '第6场', stage: '高潮', tension: 92, action: 84, emotion: 71, performanceForm: '打', label: '复仇实现', description: '家国仇怨集中爆发。' },
  { playId: 'zhaoshiguer', scene: '第7场', stage: '收束', tension: 61, action: 35, emotion: 54, performanceForm: '唱', label: '忠义回响', description: '以历史评价收尾。' },
  { playId: 'doueyuan', scene: '第1场', stage: '开端', tension: 31, action: 19, emotion: 48, performanceForm: '念', label: '处境陈述', description: '窦娥困境与家庭关系呈现。' },
  { playId: 'doueyuan', scene: '第2场', stage: '铺垫', tension: 49, action: 36, emotion: 62, performanceForm: '唱', label: '恶人逼迫', description: '冲突动因逐渐清晰。' },
  { playId: 'doueyuan', scene: '第3场', stage: '冲突升级', tension: 69, action: 54, emotion: 78, performanceForm: '做', label: '陷害成形', description: '误判链条开始闭合。' },
  { playId: 'doueyuan', scene: '第4场', stage: '高潮', tension: 95, action: 60, emotion: 96, performanceForm: '唱', label: '公堂发誓', description: '情绪与道德高度集中。' },
  { playId: 'doueyuan', scene: '第5场', stage: '收束', tension: 58, action: 24, emotion: 70, performanceForm: '念', label: '冤魂显灵', description: '由现实转入天道层面。' },
  { playId: 'doueyuan', scene: '第6场', stage: '收束', tension: 46, action: 18, emotion: 52, performanceForm: '唱', label: '昭雪结案', description: '以报应逻辑完成 closure。' },
  { playId: 'qinxianglian', scene: '第1场', stage: '开端', tension: 33, action: 26, emotion: 47, performanceForm: '唱', label: '苦境开场', description: '秦香莲处境与家庭裂痕初见。' },
  { playId: 'qinxianglian', scene: '第2场', stage: '铺垫', tension: 47, action: 35, emotion: 61, performanceForm: '念', label: '寻夫进京', description: '从家庭线转向权力空间。' },
  { playId: 'qinxianglian', scene: '第3场', stage: '冲突升级', tension: 69, action: 49, emotion: 74, performanceForm: '唱', label: '夫妻对质', description: '背叛主题达到显性层面。' },
  { playId: 'qinxianglian', scene: '第4场', stage: '转折', tension: 77, action: 57, emotion: 79, performanceForm: '做', label: '入衙申诉', description: '家庭戏结构转入公案戏结构。' },
  { playId: 'qinxianglian', scene: '第5场', stage: '高潮', tension: 91, action: 66, emotion: 82, performanceForm: '念', label: '包公审案', description: '法理与伦理正面交锋。' },
  { playId: 'qinxianglian', scene: '第6场', stage: '高潮', tension: 94, action: 70, emotion: 84, performanceForm: '打', label: '抗旨断案', description: '权力压力叠加形成第二高潮。' },
  { playId: 'qinxianglian', scene: '第7场', stage: '收束', tension: 52, action: 25, emotion: 57, performanceForm: '唱', label: '裁断落定', description: '结局回归秩序但保留余痛。' },
  { playId: 'dajinzhi', scene: '第1场', stage: '开端', tension: 24, action: 16, emotion: 32, performanceForm: '念', label: '喜庆起场', description: '以轻松氛围引出身份关系。' },
  { playId: 'dajinzhi', scene: '第2场', stage: '铺垫', tension: 41, action: 28, emotion: 50, performanceForm: '唱', label: '夫妻龃龉', description: '冲突由日常争执累积。' },
  { playId: 'dajinzhi', scene: '第3场', stage: '冲突升级', tension: 58, action: 34, emotion: 61, performanceForm: '做', label: '两家对立', description: '冲突从夫妻扩展到家族层面。' },
  { playId: 'dajinzhi', scene: '第4场', stage: '高潮', tension: 73, action: 39, emotion: 67, performanceForm: '念', label: '宫廷调停', description: '权力介入，矛盾达到顶点。' },
  { playId: 'dajinzhi', scene: '第5场', stage: '收束', tension: 38, action: 20, emotion: 41, performanceForm: '唱', label: '重归和解', description: '以秩序恢复作为结尾。' },
  { playId: 'xixiangji', scene: '第1场', stage: '开端', tension: 22, action: 15, emotion: 38, performanceForm: '念', label: '相遇契机', description: '情感线悄然启动。' },
  { playId: 'xixiangji', scene: '第2场', stage: '铺垫', tension: 36, action: 21, emotion: 59, performanceForm: '唱', label: '情意暗生', description: '抒情比重上升。' },
  { playId: 'xixiangji', scene: '第3场', stage: '铺垫', tension: 44, action: 28, emotion: 67, performanceForm: '念', label: '红娘撮合', description: '媒合者进入中心位置。' },
  { playId: 'xixiangji', scene: '第4场', stage: '冲突升级', tension: 59, action: 34, emotion: 76, performanceForm: '唱', label: '礼法阻隔', description: '外在压力进入叙事中段。' },
  { playId: 'xixiangji', scene: '第5场', stage: '转折', tension: 66, action: 39, emotion: 81, performanceForm: '做', label: '私约成形', description: '关系由暧昧转为承诺。' },
  { playId: 'xixiangji', scene: '第6场', stage: '高潮', tension: 78, action: 42, emotion: 86, performanceForm: '唱', label: '正面争取', description: '情感诉求到达高点。' },
  { playId: 'xixiangji', scene: '第7场', stage: '收束', tension: 34, action: 18, emotion: 43, performanceForm: '念', label: '圆满收尾', description: '结构以和合结束。' },
  { playId: 'mudanting', scene: '第1场', stage: '开端', tension: 20, action: 10, emotion: 41, performanceForm: '念', label: '闺阁日常', description: '平静场面为后续突破做铺垫。' },
  { playId: 'mudanting', scene: '第2场', stage: '铺垫', tension: 39, action: 18, emotion: 73, performanceForm: '唱', label: '游园惊梦', description: '情感与梦境联动启动。' },
  { playId: 'mudanting', scene: '第3场', stage: '冲突升级', tension: 52, action: 20, emotion: 84, performanceForm: '唱', label: '相思成病', description: '抒情叙事持续升温。' },
  { playId: 'mudanting', scene: '第4场', stage: '转折', tension: 61, action: 25, emotion: 87, performanceForm: '做', label: '生死越界', description: '叙事进入现实与幻想交界。' },
  { playId: 'mudanting', scene: '第5场', stage: '冲突升级', tension: 69, action: 29, emotion: 80, performanceForm: '念', label: '父权压制', description: '礼法力量回场。' },
  { playId: 'mudanting', scene: '第6场', stage: '高潮', tension: 85, action: 34, emotion: 93, performanceForm: '唱', label: '魂梦重逢', description: '爱情线与幻想线双重爆发。' },
  { playId: 'mudanting', scene: '第7场', stage: '高潮', tension: 89, action: 37, emotion: 91, performanceForm: '做', label: '还魂相认', description: '第二高潮完成叙事闭环。' },
  { playId: 'mudanting', scene: '第8场', stage: '收束', tension: 42, action: 15, emotion: 58, performanceForm: '念', label: '秩序再整合', description: '以圆满但余韵悠长收束。' },
  { playId: 'pipaji', scene: '第1场', stage: '开端', tension: 26, action: 17, emotion: 42, performanceForm: '唱', label: '婚后家境', description: '家庭结构与生活压力建场。' },
  { playId: 'pipaji', scene: '第2场', stage: '铺垫', tension: 37, action: 22, emotion: 55, performanceForm: '念', label: '奉亲难题', description: '孝与贫困交织加深。' },
  { playId: 'pipaji', scene: '第3场', stage: '冲突升级', tension: 49, action: 28, emotion: 63, performanceForm: '唱', label: '家破人离', description: '离散结构初步形成。' },
  { playId: 'pipaji', scene: '第4场', stage: '转折', tension: 57, action: 30, emotion: 68, performanceForm: '做', label: '仕途转向', description: '私人伦理与社会晋升发生交叉。' },
  { playId: 'pipaji', scene: '第5场', stage: '冲突升级', tension: 70, action: 34, emotion: 79, performanceForm: '唱', label: '赵五娘守节', description: '女性坚忍线成为情感高点。' },
  { playId: 'pipaji', scene: '第6场', stage: '高潮', tension: 82, action: 36, emotion: 83, performanceForm: '念', label: '再婚难局', description: '伦理结构进一步复杂化。' },
  { playId: 'pipaji', scene: '第7场', stage: '高潮', tension: 88, action: 39, emotion: 87, performanceForm: '唱', label: '相认与愧悔', description: '离散与孝义矛盾集中爆发。' },
  { playId: 'pipaji', scene: '第8场', stage: '收束', tension: 45, action: 19, emotion: 49, performanceForm: '念', label: '伦理归位', description: '以回环式团圆结构结尾。' },
]

export const themeGroups: Record<string, string> = {
  爱情: '情感',
  背叛: '伦理冲突',
  欲望: '情感',
  暴力: '行动',
  忠义: '政治伦理',
  复仇: '行动',
  家国: '政治伦理',
  牺牲: '政治伦理',
  冤案: '司法',
  贞节: '伦理冲突',
  报应: '司法',
  伦理: '伦理冲突',
  家庭伦理: '伦理冲突',
  法理: '司法',
  女性申诉: '伦理冲突',
  礼制: '政治伦理',
  权力: '政治伦理',
  和解: '情感',
  礼法阻隔: '政治伦理',
  媒合: '情感',
  青年自主: '情感',
  梦境: '抒情象征',
  生死: '抒情象征',
  个体欲望: '情感',
  孝义: '伦理冲突',
  离散: '情感',
  女性坚忍: '伦理冲突',
}
